before:
  hooks:
    - go mod download
builds:
  - skip: true
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^tests:'
